export type Review = {
  author: string;
  rating: number;
  comment: string;
  date: string;
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  category: string;
  price: number;
  originalPrice: number;
  description: string;
  features: string[];
  imageUrl: string;
  badge?: string;
  inStock: boolean;
  rating: number;
  reviewCount: number;
  deliveryDays: string;
  reviews: Review[];
};

export function formatPrice(price: number) {
  return price.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export const products: Product[] = [
  {
    id: "1",
    slug: "smartwatch-amoled-pro",
    name: "Smartwatch AMOLED Pro",
    shortName: "Smartwatch AMOLED",
    category: "Gadgets & Eletrônicos",
    price: 169,
    originalPrice: 220,
    description: "Smartwatch com tela AMOLED de alta resolução, monitoramento de saúde 24h, GPS integrado e até 7 dias de bateria. Resistente à água IP68.",
    features: [
      "Tela AMOLED 1.43\" sempre ativa",
      "Monitor cardíaco e SpO2 contínuo",
      "GPS integrado para corridas",
      "Bateria de até 7 dias",
      "Resistência IP68 à água",
      "Compatível com Android e iOS",
    ],
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    badge: "Mais Vendido",
    inStock: true,
    rating: 4.8,
    reviewCount: 214,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Rafael M.", rating: 5, comment: "Produto incrível, chegou antes do prazo e funcionou perfeitamente desde o primeiro uso.", date: "12/05/2026" },
      { author: "Carlos S.", rating: 5, comment: "Tela linda, bateria dura muito. Melhor custo-benefício que já vi.", date: "03/05/2026" },
      { author: "Thiago L.", rating: 4, comment: "Muito bom, só achei o GPS um pouco lento para conectar.", date: "20/04/2026" },
    ],
  },
  {
    id: "2",
    slug: "camera-wifi-360",
    name: "Câmera de Segurança Wi-Fi 360°",
    shortName: "Câmera Wi-Fi 360°",
    category: "Automação Residencial",
    price: 189,
    originalPrice: 250,
    description: "Câmera IP Full HD com rotação 360°, visão noturna colorida, detecção de movimento por IA e armazenamento em nuvem ou cartão SD.",
    features: [
      "Resolução Full HD 1080p",
      "Rotação pan/tilt 360°",
      "Visão noturna colorida até 10m",
      "Detecção de movimento por IA",
      "Áudio bidirecional",
      "App iOS e Android",
    ],
    imageUrl: "https://images.unsplash.com/photo-1595079676339-1534801ad6cf?w=600&q=80",
    badge: "Lançamento",
    inStock: true,
    rating: 4.6,
    reviewCount: 87,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Marcos A.", rating: 5, comment: "Instalação facilíssima, imagem nítida mesmo à noite. Recomendo!", date: "15/05/2026" },
      { author: "Paulo R.", rating: 4, comment: "Ótima câmera, app funciona bem. Visão noturna impressiona.", date: "28/04/2026" },
      { author: "André C.", rating: 5, comment: "Comprei para o escritório e ficou perfeito. Chegou bem embalado.", date: "10/04/2026" },
    ],
  },
  {
    id: "3",
    slug: "lanterna-tatica-recarregavel",
    name: "Lanterna Tática Recarregável USB-C",
    shortName: "Lanterna Tática",
    category: "Camping & Aventura",
    price: 89,
    originalPrice: 130,
    description: "Lanterna tática militar com LED de alto brilho, 5 modos de iluminação, carregamento USB-C e corpo em alumínio resistente a impactos.",
    features: [
      "LED de 2000 lúmens",
      "5 modos: alto, médio, baixo, strobo, SOS",
      "Carregamento rápido USB-C",
      "Corpo em alumínio T6",
      "Resistente à água IPX6",
      "Foco ajustável zoom",
    ],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    rating: 4.7,
    reviewCount: 156,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Felipe O.", rating: 5, comment: "Claridade absurda. Usei no camping e iluminou tudo. Vale cada centavo.", date: "02/05/2026" },
      { author: "Rodrigo N.", rating: 5, comment: "Robusta e leve. O zoom é excelente.", date: "18/04/2026" },
      { author: "Bruno T.", rating: 4, comment: "Muito boa, só queria que a bateria durasse um pouco mais no modo alto.", date: "05/04/2026" },
    ],
  },
  {
    id: "4",
    slug: "filtro-agua-portatil",
    name: "Filtro de Água Portátil Survival",
    shortName: "Filtro de Água Portátil",
    category: "Camping & Aventura",
    price: 129,
    originalPrice: 180,
    description: "Filtro de água portátil com membrana hollow fiber que remove 99,9999% de bactérias. Essencial para trilhas, camping e emergências.",
    features: [
      "Remove 99,9999% de bactérias",
      "Filtra até 100.000 litros",
      "Peso ultraleve: apenas 57g",
      "Conexão direta na garrafa",
      "Sem necessidade de produtos químicos",
      "Inclui canudo e bolsa de hidratação",
    ],
    imageUrl: "https://images.unsplash.com/photo-1622495966027-e7f40150eb08?w=600&q=80",
    badge: "Essencial",
    inStock: true,
    rating: 4.9,
    reviewCount: 98,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Lucas B.", rating: 5, comment: "Levei em uma trilha de 5 dias no Pantanal. Funcionou perfeitamente.", date: "07/05/2026" },
      { author: "Diego F.", rating: 5, comment: "Produto essencial para quem faz trilha. Leve e confiável.", date: "22/04/2026" },
      { author: "Henrique V.", rating: 5, comment: "Qualidade surpreendente para o preço. Recomendo a todos os aventureiros.", date: "01/04/2026" },
    ],
  },
  {
    id: "5",
    slug: "fechadura-digital-biometrica",
    name: "Fechadura Digital Biométrica",
    shortName: "Fechadura Digital",
    category: "Automação Residencial",
    price: 269,
    originalPrice: 380,
    description: "Fechadura inteligente com biometria, senha numérica, cartão RFID e controle pelo app. Instalação simples sem obra.",
    features: [
      "Reconhecimento biométrico em 0,5s",
      "4 formas de acesso: digital, senha, RFID, app",
      "Histórico de acessos no app",
      "Alarme anti-arrombamento",
      "Bateria 4xAA com indicador de nível",
      "Instalação sem obra (retrofit)",
    ],
    imageUrl: "https://images.unsplash.com/photo-1609743522653-52354461eb27?w=600&q=80",
    inStock: true,
    rating: 4.7,
    reviewCount: 63,
    deliveryDays: "6–9 dias úteis",
    reviews: [
      { author: "Gustavo P.", rating: 5, comment: "Instalei sozinho em 30 minutos. Biometria rápida e precisa.", date: "10/05/2026" },
      { author: "Alexandre K.", rating: 4, comment: "Ótima fechadura, app funciona bem. Chegou com todos os acessórios.", date: "25/04/2026" },
      { author: "Ricardo M.", rating: 5, comment: "Segurança total. Já tentaram arrombar e o alarme funcionou.", date: "08/04/2026" },
    ],
  },
  {
    id: "6",
    slug: "fone-tws-bluetooth",
    name: "Fone TWS Bluetooth 5.3 com ANC",
    shortName: "Fone TWS ANC",
    category: "Gadgets & Eletrônicos",
    price: 149,
    originalPrice: 220,
    description: "Fone de ouvido sem fio com cancelamento ativo de ruído, até 30h de bateria total e conexão Bluetooth 5.3 de baixa latência.",
    features: [
      "Cancelamento ativo de ruído (ANC)",
      "Bluetooth 5.3 com latência <60ms",
      "6h por carga + 24h no estojo",
      "Microfone com redução de ruído ENC",
      "Resistência à água IPX5",
      "Controle por toque",
    ],
    imageUrl: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80",
    badge: "Top Gadget",
    inStock: true,
    rating: 4.6,
    reviewCount: 189,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Gabriel S.", rating: 5, comment: "Som incrível, ANC funciona de verdade. Uso no trabalho todo dia.", date: "14/05/2026" },
      { author: "Matheus R.", rating: 4, comment: "Muito bom para o preço. Bateria dura bastante.", date: "30/04/2026" },
      { author: "Igor A.", rating: 5, comment: "Comprei e me arrependi de ter esperado tanto. Melhor fone que tive.", date: "12/04/2026" },
    ],
  },
  {
    id: "7",
    slug: "power-bank-65w",
    name: "Power Bank Ultra-Slim 65W 20000mAh",
    shortName: "Power Bank 65W",
    category: "Gadgets & Eletrônicos",
    price: 189,
    originalPrice: 260,
    description: "Carregador portátil ultrafino de 20.000mAh com saída 65W USB-C, capaz de carregar notebooks, tablets e celulares rapidamente.",
    features: [
      "Capacidade de 20.000mAh",
      "Saída USB-C 65W (carrega notebooks)",
      "2 saídas USB-A + 1 USB-C",
      "Display LED de porcentagem",
      "Design ultrafino 13mm",
      "Certificação CE e RoHS",
    ],
    imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
    inStock: true,
    rating: 4.5,
    reviewCount: 72,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Leandro C.", rating: 5, comment: "Carregou meu notebook e celular em viagem. Indispensável.", date: "08/05/2026" },
      { author: "Vitor H.", rating: 4, comment: "Muito fino para a capacidade. Funciona muito bem.", date: "19/04/2026" },
      { author: "Caio M.", rating: 5, comment: "Excelente produto. Entrega rápida e bem embalado.", date: "02/04/2026" },
    ],
  },
  {
    id: "8",
    slug: "massageador-percussivo",
    name: "Massageador Percussivo Pós-Treino",
    shortName: "Massageador Percussivo",
    category: "Gadgets & Eletrônicos",
    price: 259,
    originalPrice: 380,
    description: "Pistola de massagem percussiva com 6 cabeças intercambiáveis, 20 velocidades e motor silencioso. Recuperação muscular profissional.",
    features: [
      "Motor silencioso <45dB",
      "20 níveis de intensidade",
      "6 cabeças intercambiáveis",
      "Bateria de 2400mAh (6h de uso)",
      "Carregamento USB-C",
      "Maleta de transporte inclusa",
    ],
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80",
    badge: "Fitness",
    inStock: true,
    rating: 4.8,
    reviewCount: 134,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Eduardo N.", rating: 5, comment: "Meu personal indicou e não me arrependi. Recuperação muito mais rápida.", date: "11/05/2026" },
      { author: "Fábio S.", rating: 5, comment: "Silencioso e potente. As 6 cabeças atendem todos os grupos musculares.", date: "27/04/2026" },
      { author: "Samuel T.", rating: 4, comment: "Muito bom, só achei que poderia vir com case mais robusto.", date: "09/04/2026" },
    ],
  },
  {
    id: "9",
    slug: "suporte-magnetico-wireless",
    name: "Suporte Veicular Magnético com Wireless",
    shortName: "Suporte Magnético Wireless",
    category: "Gadgets & Eletrônicos",
    price: 99,
    originalPrice: 149,
    description: "Suporte veicular com carregamento wireless 15W MagSafe. Fixação magnética automática, rotação 360° e braço telescópico.",
    features: [
      "Carregamento wireless 15W",
      "Compatível com MagSafe",
      "Fixação magnética automática",
      "Rotação 360°",
      "Braço telescópico ajustável",
      "Fixação no painel ou ar-condicionado",
    ],
    imageUrl: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    inStock: true,
    rating: 4.4,
    reviewCount: 58,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Renato B.", rating: 5, comment: "Encaixa o celular automaticamente. Praticidade total no trânsito.", date: "06/05/2026" },
      { author: "Vinícius L.", rating: 4, comment: "Muito bom, carrega rápido. Fixação no painel é firme.", date: "21/04/2026" },
      { author: "Otávio F.", rating: 4, comment: "Produto de qualidade. Chegou bem antes do prazo.", date: "03/04/2026" },
    ],
  },
  {
    id: "10",
    slug: "compressor-ar-portatil",
    name: "Compressor de Ar Portátil Digital",
    shortName: "Compressor Portátil",
    category: "Gadgets & Eletrônicos",
    price: 139,
    originalPrice: 200,
    description: "Compressor de ar digital portátil com desligamento automático, display LED e bateria interna. Ideal para pneus, bolas e colchões infláveis.",
    features: [
      "Pressão máxima de 150 PSI",
      "Desligamento automático no alvo",
      "Display LED de pressão",
      "Bateria de 6000mAh integrada",
      "3 bicos adaptadores inclusos",
      "Lanterna de emergência integrada",
    ],
    imageUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&q=80",
    inStock: true,
    rating: 4.6,
    reviewCount: 91,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Danilo C.", rating: 5, comment: "Salvou minha vida em uma viagem com pneu murcho. Essencial no carro.", date: "09/05/2026" },
      { author: "Murilo A.", rating: 4, comment: "Compacto e eficiente. O desligamento automático é muito útil.", date: "24/04/2026" },
      { author: "Sérgio V.", rating: 5, comment: "Melhor compra do mês. Qualidade muito acima do esperado.", date: "07/04/2026" },
    ],
  },
  {
    id: "11",
    slug: "alicate-multifuncional-14em1",
    name: "Alicate Multifuncional 14-em-1",
    shortName: "Alicate Multifuncional",
    category: "Ferramentas & Utilidades",
    price: 119,
    originalPrice: 170,
    description: "Alicate multi-tool profissional em aço inox com 14 funções. Compacto, robusto e com estojo de couro. O canivete suíço das ferramentas.",
    features: [
      "14 funções em uma só ferramenta",
      "Aço inox 420HC premium",
      "Travas de segurança em todas as lâminas",
      "Inclui estojo de couro",
      "Peso de apenas 200g",
      "Garantia do fabricante",
    ],
    imageUrl: "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&q=80",
    badge: "Mais Vendido",
    inStock: true,
    rating: 4.8,
    reviewCount: 203,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Cláudio M.", rating: 5, comment: "Melhor presente que ganhei. Uso todo dia, qualidade excepcional.", date: "13/05/2026" },
      { author: "Júlio R.", rating: 5, comment: "Acabamento perfeito. Travas de segurança funcionam muito bem.", date: "29/04/2026" },
      { author: "Nelson S.", rating: 4, comment: "Produto robusto e versátil. Estojo de couro é um bônus.", date: "11/04/2026" },
    ],
  },
  {
    id: "12",
    slug: "kit-chaves-precisao",
    name: "Kit Chaves de Precisão 115 Peças",
    shortName: "Kit Chaves 115 Peças",
    category: "Ferramentas & Utilidades",
    price: 89,
    originalPrice: 130,
    description: "Kit completo com 115 bits de precisão para eletrônicos, notebooks, consoles e smartphones. Inclui bits para parafusos pentalobe e torx.",
    features: [
      "115 bits de precisão em aço S2",
      "Inclui pentalobe, torx, tri-wing e mais",
      "Cabo magnético com suporte giratório",
      "Estojo organizador com encaixe individual",
      "Pinça e alavanca de abertura inclusas",
      "Compatível com iPhone, Samsung e mais",
    ],
    imageUrl: "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=600&q=80",
    inStock: true,
    rating: 4.7,
    reviewCount: 118,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Tiago F.", rating: 5, comment: "Consertei meu iPhone com esse kit. Tem tudo que precisa.", date: "05/05/2026" },
      { author: "Alan P.", rating: 5, comment: "Qualidade dos bits é muito boa. Estojo organizado e prático.", date: "17/04/2026" },
      { author: "Roberto L.", rating: 4, comment: "Ótimo kit. Só o cabo poderia ser um pouco mais longo.", date: "01/04/2026" },
    ],
  },
  {
    id: "13",
    slug: "nivel-laser-linha-cruzada",
    name: "Nível a Laser de Linha Cruzada",
    shortName: "Nível a Laser",
    category: "Ferramentas & Utilidades",
    price: 159,
    originalPrice: 230,
    description: "Nível laser de linha cruzada com auto-nivelamento, alcance de 15m e tripé incluso. Ideal para instalações, obras e reformas.",
    features: [
      "Linha horizontal e vertical simultâneas",
      "Auto-nivelamento em ±4°",
      "Alcance de até 15 metros",
      "Tripé magnético incluso",
      "Modo pêndulo e modo manual",
      "Bateria de 3xAA",
    ],
    imageUrl: "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&q=80",
    inStock: true,
    rating: 4.5,
    reviewCount: 44,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Walter C.", rating: 5, comment: "Precisão impressionante. Reformei meu apartamento com ele.", date: "04/05/2026" },
      { author: "César A.", rating: 4, comment: "Funciona muito bem. O tripé magnético é um diferencial.", date: "16/04/2026" },
      { author: "Flávio R.", rating: 5, comment: "Comprei para instalar porcelanato. Linha certinha o tempo todo.", date: "28/03/2026" },
    ],
  },
  {
    id: "14",
    slug: "multimetro-digital",
    name: "Multímetro Digital Profissional",
    shortName: "Multímetro Digital",
    category: "Ferramentas & Utilidades",
    price: 99,
    originalPrice: 150,
    description: "Multímetro digital com display backlight, medição de tensão AC/DC, corrente, resistência, temperatura e testador de diodo.",
    features: [
      "Display LCD com backlight",
      "Tensão AC/DC até 600V",
      "Corrente até 10A",
      "Medição de temperatura com termopar",
      "Testador de continuidade com buzzer",
      "Proteção contra sobrecarga",
    ],
    imageUrl: "https://images.unsplash.com/photo-1601972599720-36938d4ecd31?w=600&q=80",
    inStock: true,
    rating: 4.6,
    reviewCount: 67,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Emerson D.", rating: 5, comment: "Preciso e fácil de usar. Ótimo para uso doméstico e profissional.", date: "07/05/2026" },
      { author: "Adilson P.", rating: 4, comment: "Muito bom. O termopar incluso é um bônus excelente.", date: "20/04/2026" },
      { author: "Rubens H.", rating: 5, comment: "Qualidade de profissional a preço acessível.", date: "04/04/2026" },
    ],
  },
  {
    id: "15",
    slug: "garrafa-termica-1l",
    name: "Garrafa Térmica Inox 1 Litro",
    shortName: "Garrafa Térmica 1L",
    category: "Camping & Aventura",
    price: 109,
    originalPrice: 160,
    description: "Garrafa térmica de aço inox de dupla parede com vácuo. Mantém bebidas quentes por 12h e frias por 24h. Resistente a impactos.",
    features: [
      "Parede dupla com isolamento a vácuo",
      "Quente 12h / Frio 24h",
      "Capacidade de 1 litro",
      "Aço inox 18/8 food grade",
      "Tampa com rosca hermética",
      "Livre de BPA",
    ],
    imageUrl: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    badge: "Essencial",
    inStock: true,
    rating: 4.9,
    reviewCount: 312,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Jonathan K.", rating: 5, comment: "Café quente por mais de 12h testado. Produto incrível.", date: "15/05/2026" },
      { author: "Cristian O.", rating: 5, comment: "Qualidade excelente. Já caiu e não amassou.", date: "01/05/2026" },
      { author: "Welton A.", rating: 5, comment: "Indispensável para o trabalho. Minha água fica gelada o dia todo.", date: "14/04/2026" },
    ],
  },
  {
    id: "16",
    slug: "canivete-multiferramenta",
    name: "Canivete Multiferramenta Survival",
    shortName: "Canivete Multiferramenta",
    category: "Camping & Aventura",
    price: 79,
    originalPrice: 120,
    description: "Canivete tático multiferramenta com 12 funções, lâmina em aço inox 440C e cabo ergonômico. Compacto para trilhas e aventuras ao ar livre.",
    features: [
      "12 funções integradas",
      "Lâmina em aço inox 440C",
      "Abridor de garrafa e lata",
      "Serrote, tesoura e lima",
      "Clip de bolso incluso",
      "Estojo tático incluso",
    ],
    imageUrl: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=600&q=80",
    inStock: true,
    rating: 4.5,
    reviewCount: 89,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Marcelo B.", rating: 5, comment: "Compacto e robusto. Uso em todas as trilhas.", date: "10/05/2026" },
      { author: "Patrick S.", rating: 4, comment: "Bom acabamento. A lâmina vem bem afiada.", date: "23/04/2026" },
      { author: "Evandro M.", rating: 5, comment: "Presente perfeito para quem gosta de aventura.", date: "06/04/2026" },
    ],
  },
  {
    id: "17",
    slug: "headlamp-led",
    name: "Lanterna de Cabeça LED 1000 Lúmens",
    shortName: "Lanterna de Cabeça LED",
    category: "Camping & Aventura",
    price: 69,
    originalPrice: 110,
    description: "Headlamp com LED de 1000 lúmens, 5 modos de iluminação, carregamento USB-C e ajuste de ângulo. Leve e resistente à água IPX6.",
    features: [
      "1000 lúmens no modo máximo",
      "5 modos incluindo luz vermelha",
      "Carregamento USB-C",
      "Resistência IPX6 à água",
      "Peso de apenas 68g",
      "Ângulo ajustável 45°",
    ],
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80",
    inStock: true,
    rating: 4.7,
    reviewCount: 145,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Alexsandro R.", rating: 5, comment: "Leve e potente. Usei em espeleologia e foi perfeita.", date: "12/05/2026" },
      { author: "Silvio N.", rating: 5, comment: "Luz vermelha é ótima para não perder a visão noturna.", date: "26/04/2026" },
      { author: "Adão C.", rating: 4, comment: "Muito boa. A regulagem do ângulo é precisa.", date: "09/04/2026" },
    ],
  },
  {
    id: "18",
    slug: "capa-impermeavel-mochila",
    name: "Capa Impermeável para Mochila",
    shortName: "Capa para Mochila",
    category: "Camping & Aventura",
    price: 59,
    originalPrice: 90,
    description: "Capa protetora impermeável para mochilas de 20L a 70L. Material Oxford 210D ultraresistente, guarda fácil e alça reflexiva para segurança.",
    features: [
      "Compatível com mochilas 20L a 70L",
      "Material Oxford 210D impermeável",
      "Faixa reflexiva para segurança",
      "Dobra em bolsa compacta",
      "Cordão elástico de fixação",
      "5 tamanhos disponíveis",
    ],
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    inStock: true,
    rating: 4.4,
    reviewCount: 56,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Ronan P.", rating: 5, comment: "Salvou minha mochila numa chuva forte na trilha. Vale muito.", date: "08/05/2026" },
      { author: "Adriano T.", rating: 4, comment: "Fácil de guardar e coloca rápido quando precisa.", date: "22/04/2026" },
      { author: "Elton V.", rating: 4, comment: "Boa qualidade, material resistente.", date: "05/04/2026" },
    ],
  },
  {
    id: "19",
    slug: "lampada-inteligente-rgb",
    name: "Lâmpada Inteligente RGB Wi-Fi",
    shortName: "Lâmpada RGB Wi-Fi",
    category: "Automação Residencial",
    price: 59,
    originalPrice: 90,
    description: "Lâmpada LED inteligente 16 milhões de cores RGB, controle por app, compatível com Alexa e Google Home. Sem hub necessário.",
    features: [
      "16 milhões de cores RGB + branco quente/frio",
      "Controle por app ou voz",
      "Compatível com Alexa e Google Home",
      "Potência 9W equivale a 60W",
      "Vida útil de 25.000 horas",
      "Cenas e horários programáveis",
    ],
    imageUrl: "https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&q=80",
    badge: "Smart Home",
    inStock: true,
    rating: 4.5,
    reviewCount: 178,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Davi L.", rating: 5, comment: "Configurou em 2 minutos com a Alexa. Cores incríveis.", date: "14/05/2026" },
      { author: "Natan S.", rating: 4, comment: "App funciona bem. Cenas de cinema e festa são demais.", date: "28/04/2026" },
      { author: "Kevin O.", rating: 5, comment: "Transformou o quarto. Preço ótimo para essa qualidade.", date: "10/04/2026" },
    ],
  },
  {
    id: "20",
    slug: "tomada-inteligente-wifi",
    name: "Tomada Inteligente Wi-Fi 16A",
    shortName: "Tomada Inteligente Wi-Fi",
    category: "Automação Residencial",
    price: 69,
    originalPrice: 100,
    description: "Tomada smart Wi-Fi 16A com monitoramento de consumo de energia, timer programável, controle por voz e proteção contra sobrecarga.",
    features: [
      "Controle remoto por app",
      "Monitoramento de consumo em tempo real",
      "Compatível com Alexa e Google Home",
      "Timer e agendamentos programáveis",
      "Proteção contra sobrecarga e surtos",
      "Instalação plug & play",
    ],
    imageUrl: "https://images.unsplash.com/photo-1586473219010-2ffc57b0d282?w=600&q=80",
    inStock: true,
    rating: 4.6,
    reviewCount: 93,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Luan C.", rating: 5, comment: "Monitoramento de consumo é muito útil. Descobri que meu ar-condicionado gasta muito.", date: "11/05/2026" },
      { author: "Yuri M.", rating: 4, comment: "Fácil de instalar e configurar. App é intuitivo.", date: "25/04/2026" },
      { author: "Enzo F.", rating: 5, comment: "Comprei 4 unidades. Funcionam perfeitamente com a Alexa.", date: "08/04/2026" },
    ],
  },
];
