export type Review = {
  author: string;
  rating: number;
  comment: string;
  date: string;
};

export type Product = {
  id: string;
  slug: string;
  name: string;
  shortName: string;
  category: string;
  price: number;
  originalPrice: number;
  description: string;
  features: string[];
  imageUrl: string;
  images?: string[];
  badge?: string;
  inStock: boolean;
  rating: number;
  reviewCount: number;
  deliveryDays: string;
  reviews: Review[];
};

export function formatPrice(price: number) {
  return price.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
}

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export const products: Product[] = [
  {
    id: "1",
    slug: "smartwatch-amoled-pro",
    name: "Smartwatch AMOLED Pro",
    shortName: "Smartwatch AMOLED",
    category: "Gadgets & Eletrônicos",
    price: 169,
    originalPrice: 220,
    description: "Smartwatch com tela AMOLED de alta resolução, monitoramento de saúde 24h, GPS integrado e até 7 dias de bateria. Resistente à água IP68.",
    features: [
      "Tela AMOLED 1.43\" sempre ativa",
      "Monitor cardíaco e SpO2 contínuo",
      "GPS integrado para corridas",
      "Bateria de até 7 dias",
      "Resistência IP68 à água",
      "Compatível com Android e iOS",
    ],
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80",
    badge: "Mais Vendido",
    inStock: true,
    rating: 4.8,
    reviewCount: 214,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Rafael M.", rating: 5, comment: "Produto incrível, chegou antes do prazo e funcionou perfeitamente desde o primeiro uso.", date: "12/05/2026" },
      { author: "Carlos S.", rating: 5, comment: "Tela linda, bateria dura muito. Melhor custo-benefício que já vi.", date: "03/05/2026" },
      { author: "Thiago L.", rating: 4, comment: "Muito bom, só achei o GPS um pouco lento para conectar.", date: "20/04/2026" },
    ],
  },
  {
    id: "2",
    slug: "fone-bluetooth-anc",
    name: "Fone de Ouvido Bluetooth ANC Pro",
    shortName: "Fone Bluetooth ANC",
    category: "Gadgets & Eletrônicos",
    price: 189,
    originalPrice: 280,
    description: "Fone over-ear com cancelamento ativo de ruído (ANC), drivers de 40mm, bateria de 30h e dobramento compacto para viagens.",
    features: [
      "Cancelamento ativo de ruído (ANC)",
      "Drivers 40mm com graves potentes",
      "Bateria de até 30 horas",
      "Dobrável para transporte",
      "Bluetooth 5.3",
      "Microfone integrado para chamadas",
    ],
    imageUrl: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80",
    badge: "Destaque",
    inStock: true,
    rating: 4.7,
    reviewCount: 189,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Lucas P.", rating: 5, comment: "O ANC é impressionante, bloqueia todo o barulho do escritório.", date: "15/05/2026" },
      { author: "Amanda R.", rating: 4, comment: "Confortável e com ótimo som. Bateria realmente dura muito.", date: "07/05/2026" },
      { author: "Felipe G.", rating: 5, comment: "Melhor fone que já tive. Vale muito o preço.", date: "28/04/2026" },
    ],
  },
  {
    id: "3",
    slug: "mini-projetor-portatil",
    name: "Mini Projetor Portátil Full HD",
    shortName: "Mini Projetor Full HD",
    category: "Gadgets & Eletrônicos",
    price: 299,
    originalPrice: 450,
    description: "Projetor compacto Full HD 1080p com 200 lumens, bateria interna de 2h, conexão HDMI e USB. Perfeito para filmes ao ar livre.",
    features: [
      "Resolução Full HD 1080p",
      "200 lumens de brilho",
      "Bateria interna de 2 horas",
      "Entrada HDMI, USB e AUX",
      "Alto-falante integrado",
      "Peso apenas 380g",
    ],
    imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&q=80",
    badge: "Novidade",
    inStock: true,
    rating: 4.5,
    reviewCount: 97,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Mariana T.", rating: 5, comment: "Levei pro camping e foi um sucesso. Imagem nítida mesmo na tela improvisada.", date: "10/05/2026" },
      { author: "João V.", rating: 4, comment: "Muito prático. Perfeito para apresentações rápidas.", date: "02/05/2026" },
      { author: "Beatriz N.", rating: 5, comment: "Qualidade de imagem surpreende para o tamanho.", date: "18/04/2026" },
    ],
  },
  {
    id: "4",
    slug: "canivete-multiuso-victorinox",
    name: "Canivete Multiuso 14 em 1",
    shortName: "Canivete Multiuso",
    category: "Ferramentas & Utilidades",
    price: 89,
    originalPrice: 130,
    description: "Canivete multifuncional com 14 ferramentas em aço inox, cabo ergonômico e estojo de couro. Essencial para camping, trilhas e emergências.",
    features: [
      "14 ferramentas em aço inox",
      "Faca, tesoura, chave de fenda",
      "Serra, abridor, lixa de unhas",
      "Cabo ergonômico antiderrapante",
      "Estojo de couro incluso",
      "Peso 120g",
    ],
    imageUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80",
    inStock: true,
    rating: 4.9,
    reviewCount: 342,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Pedro A.", rating: 5, comment: "Qualidade excepcional. Uso no camping todo fim de semana.", date: "14/05/2026" },
      { author: "Ricardo O.", rating: 5, comment: "Ferramentas muito bem acabadas e resistentes.", date: "06/05/2026" },
      { author: "Gustavo B.", rating: 4, comment: "Excelente para trilhas. Só o estojo que poderia ser melhor.", date: "22/04/2026" },
    ],
  },
  {
    id: "5",
    slug: "lanterna-tatica-led",
    name: "Lanterna Tática LED 2000 Lumens",
    shortName: "Lanterna Tática 2000lm",
    category: "Ferramentas & Utilidades",
    price: 79,
    originalPrice: 120,
    description: "Lanterna tática militar com LED CREE de 2000 lumens, alcance de 500m, 5 modos de iluminação e resistência IP67 à água e impacto.",
    features: [
      "2000 lumens com LED CREE",
      "Alcance de até 500 metros",
      "5 modos: alto, médio, baixo, estroboscópio, SOS",
      "Resistência IP67 à água",
      "Corpo em alumínio aeronáutico",
      "Bateria recarregável inclusa",
    ],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    rating: 4.7,
    reviewCount: 276,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "André C.", rating: 5, comment: "Iluminação absurda! Uso em pescaria e é impressionante.", date: "11/05/2026" },
      { author: "Marcos F.", rating: 5, comment: "Resistente e potente. Caiu na lama e continuou funcionando.", date: "04/05/2026" },
      { author: "Daniel R.", rating: 4, comment: "Ótima lanterna. Bateria dura bastante no modo médio.", date: "19/04/2026" },
    ],
  },
  {
    id: "6",
    slug: "kit-ferramentas-precision",
    name: "Kit Ferramentas de Precisão 46 peças",
    shortName: "Kit Ferramentas 46pç",
    category: "Ferramentas & Utilidades",
    price: 99,
    originalPrice: 150,
    description: "Kit completo com 46 bits e chaves de precisão para eletrônicos, notebooks, celulares e consoles. Maleta magnética organizada.",
    features: [
      "46 bits e chaves de precisão",
      "Compatível com iPhone, Samsung, notebooks",
      "Magnetizador/desmagnetizador incluso",
      "Maleta com compartimentos organizados",
      "Aço cromo-vanádio de alta dureza",
      "Cabo giratório com grip emborrachado",
    ],
    imageUrl: "https://images.unsplash.com/photo-1581092334247-ddef2a41a4e4?w=600&q=80",
    inStock: true,
    rating: 4.8,
    reviewCount: 198,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Eduardo L.", rating: 5, comment: "Perfeito para manutenção de eletrônicos. Bits encaixam perfeitamente.", date: "09/05/2026" },
      { author: "Roberto M.", rating: 4, comment: "Muito completo. Usei para trocar a bateria do iPhone sem problema.", date: "01/05/2026" },
      { author: "Henrique T.", rating: 5, comment: "Qualidade excelente. Maleta muito bem organizada.", date: "17/04/2026" },
    ],
  },
  {
    id: "7",
    slug: "power-bank-basike",
    name: "Power Bank 26.800mAh Basike com Display",
    shortName: "Power Bank Basike",
    category: "Gadgets & Eletrônicos",
    price: 139,
    originalPrice: 200,
    description: "Carregador portátil Basike de 26.800mAh com display LED, 3 saídas USB, entrada USB-C e carga rápida 22.5W. Ideal para viagens longas e camping.",
    features: [
      "Capacidade real de 26.800mAh",
      "Carga rápida 22.5W",
      "3 saídas USB + 1 entrada USB-C",
      "Display LED com indicador de porcentagem",
      "Proteção contra sobrecarga, curto e superaquecimento",
      "Carrega até 6x um smartphone comum",
    ],
    imageUrl: "https://github.com/drdiegopradomed/Gear-Up-Prado/raw/main/public/images/power-bank-basike-7.jpg",
    images: [
      "https://github.com/drdiegopradomed/Gear-Up-Prado/raw/main/public/images/power-bank-basike-8.jpg",
      "https://github.com/drdiegopradomed/Gear-Up-Prado/raw/main/public/images/power-bank-basike-9.jpg",
      "https://github.com/drdiegopradomed/Gear-Up-Prado/raw/main/public/images/power-bank-basike-10.jpg",
      "https://github.com/drdiegopradomed/Gear-Up-Prado/raw/main/public/images/power-bank-basike-11.jpg",
    ],
    badge: "Camping",
    inStock: true,
    rating: 4.7,
    reviewCount: 523,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Fernanda C.", rating: 5, comment: "Carregou meu celular 5 vezes em um camping de 3 dias. Perfeito!", date: "13/05/2026" },
      { author: "Paulo H.", rating: 4, comment: "Capacidade real impressiona. Display é muito útil para saber quanto resta.", date: "05/05/2026" },
      { author: "Isabela W.", rating: 5, comment: "Ótimo para viagens. Passou na triagem do aeroporto sem problema.", date: "21/04/2026" },
    ],
  },
  {
    id: "8",
    slug: "barraca-camping-2-pessoas",
    name: "Barraca de Camping 2 Pessoas Impermeável",
    shortName: "Barraca Camping 2p",
    category: "Camping & Aventura",
    price: 219,
    originalPrice: 320,
    description: "Barraca de camping para 2 pessoas com cobertura dupla impermeável, montagem rápida em 10 minutos e bolsa de transporte compacta.",
    features: [
      "Impermeável — coluna de água 3000mm",
      "Montagem rápida em 10 minutos",
      "Cabine dupla com área de entrada",
      "Ventilação anti-condensação",
      "Estacas e cordas inclusas",
      "Peso total 2,1kg",
    ],
    imageUrl: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&q=80",
    badge: "Camping",
    inStock: true,
    rating: 4.6,
    reviewCount: 143,
    deliveryDays: "6–10 dias úteis",
    reviews: [
      { author: "Renata A.", rating: 5, comment: "Resistiu a chuva forte no Ibitipoca. Montagem super rápida.", date: "08/05/2026" },
      { author: "Caio M.", rating: 4, comment: "Boa barraca para o preço. Ventilação poderia ser melhor no calor.", date: "30/04/2026" },
      { author: "Natalia S.", rating: 5, comment: "Leve e compacta. Coube facilmente na mochila de trilha.", date: "16/04/2026" },
    ],
  },
  {
    id: "9",
    slug: "saco-dormir-camping",
    name: "Saco de Dormir Camping -5°C Mommy",
    shortName: "Saco de Dormir -5°C",
    category: "Camping & Aventura",
    price: 169,
    originalPrice: 250,
    description: "Saco de dormir tipo múmia para temperaturas até -5°C, recheio de fibra siliconizada, zíper duplo e compressão em saco compacto.",
    features: [
      "Conforto até -5°C",
      "Formato múmia para maior calor",
      "Recheio de fibra siliconizada antimofo",
      "Zíper duplo com protetor antifrio",
      "Comprime para 30×20cm",
      "Peso 1,2kg",
    ],
    imageUrl: "https://images.unsplash.com/photo-1559827291-72ee739d0d9a?w=600&q=80",
    inStock: true,
    rating: 4.8,
    reviewCount: 89,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Victor H.", rating: 5, comment: "Usei na Serra Gaúcha no inverno. Fiquei quentinho a noite toda.", date: "07/05/2026" },
      { author: "Sabrina L.", rating: 5, comment: "Levinho e compacto. Cabe sem problema na mochila de 40L.", date: "29/04/2026" },
      { author: "Patrick R.", rating: 4, comment: "Muito bom para o preço. Zíper funciona bem mesmo no frio.", date: "14/04/2026" },
    ],
  },
  {
    id: "10",
    slug: "fogareiro-gas-camping",
    name: "Fogareiro a Gás Portátil Camping",
    shortName: "Fogareiro Portátil",
    category: "Camping & Aventura",
    price: 99,
    originalPrice: 149,
    description: "Fogareiro compacto a gás com ignição piezoelétrica, suporte dobrável para panelas e válvula de pressão de segurança. Compatível com cartucho ISO.",
    features: [
      "Ignição piezoelétrica sem fósforo",
      "Compatível com cartuchos ISO 100g/230g",
      "Suporte dobrável para panelas até 20cm",
      "Válvula de segurança antipressão",
      "Peso 280g sem cartucho",
      "Potência 2500W",
    ],
    imageUrl: "https://images.unsplash.com/photo-1617197417293-e9b8b36cf2ac?w=600&q=80",
    badge: "Camping",
    inStock: true,
    rating: 4.9,
    reviewCount: 211,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Leandro B.", rating: 5, comment: "Perfeito para o camping! Ferve água em menos de 3 minutos.", date: "10/05/2026" },
      { author: "Daniela F.", rating: 5, comment: "Leve e prático. Nunca falhou em nenhuma trilha.", date: "02/05/2026" },
      { author: "Rodrigo T.", rating: 4, comment: "Ótimo produto. Cartucho de gás é fácil de achar.", date: "18/04/2026" },
    ],
  },
  {
    id: "11",
    slug: "mochila-hidratacao-trail",
    name: "Mochila de Hidratação Trail 15L",
    shortName: "Mochila Hidratação 15L",
    category: "Camping & Aventura",
    price: 149,
    originalPrice: 210,
    description: "Mochila de trail com reservatório de hidratação 2L, costas ventiladas, porta objetos de valor e suporte de postura para longas trilhas.",
    features: [
      "Reservatório de hidratação 2L incluso",
      "Costas ventiladas com canal de ar",
      "15L de capacidade total",
      "Bolso oculto antifurto",
      "Cinto estabilizador no quadril",
      "Capa de chuva inclusa",
    ],
    imageUrl: "https://images.unsplash.com/photo-1622260614153-03223fb72052?w=600&q=80",
    inStock: true,
    rating: 4.6,
    reviewCount: 134,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Aline M.", rating: 5, comment: "Usei na Pedra do Baú. Encaixe perfeito, não senti o peso.", date: "09/05/2026" },
      { author: "Rodrigo S.", rating: 4, comment: "Muito confortável. Hidratação é essencial nas trilhas longas.", date: "01/05/2026" },
      { author: "Cristina V.", rating: 5, comment: "Capa de chuva salva vidas. Tudo ficou seco na tempestade.", date: "17/04/2026" },
    ],
  },
  {
    id: "12",
    slug: "kit-sobrevivencia-emergencia",
    name: "Kit de Sobrevivência e Emergência 15 itens",
    shortName: "Kit Sobrevivência 15pç",
    category: "Camping & Aventura",
    price: 119,
    originalPrice: 170,
    description: "Kit completo com 15 itens de sobrevivência: pederneira, apito de emergência, bússola, faca, cobertor térmico, cordas e muito mais.",
    features: [
      "Pederneira para acender fogo",
      "Bússola de orientação",
      "Faca de sobrevivência com bainha",
      "Apito de emergência",
      "Cobertor térmico 160×210cm",
      "Corda de paracord 4m inclusa",
    ],
    imageUrl: "https://images.unsplash.com/photo-1597348989936-54bb3de37762?w=600&q=80",
    badge: "Aventura",
    inStock: true,
    rating: 4.7,
    reviewCount: 167,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Mateus C.", rating: 5, comment: "Excelente kit. Usei a pederneira várias vezes no camping.", date: "08/05/2026" },
      { author: "Juliana A.", rating: 4, comment: "Muito completo para o preço. Faca é resistente.", date: "30/04/2026" },
      { author: "Leonardo P.", rating: 5, comment: "Presente perfeito para quem curte trilhas.", date: "15/04/2026" },
    ],
  },
  {
    id: "13",
    slug: "hub-usb-c-7-em-1",
    name: "Hub USB-C 7 em 1 com HDMI 4K",
    shortName: "Hub USB-C 7 em 1",
    category: "Gadgets & Eletrônicos",
    price: 119,
    originalPrice: 180,
    description: "Hub USB-C multifuncional com saída HDMI 4K, 3 portas USB-A 3.0, leitor SD/TF, USB-C PD 100W e Ethernet Gigabit. Compatível com MacBook e notebooks.",
    features: [
      "Saída HDMI 4K@60Hz",
      "3x USB-A 3.0 (5Gbps)",
      "USB-C Power Delivery 100W",
      "Leitor SD e MicroSD simultâneo",
      "Ethernet Gigabit integrada",
      "Compatível com MacBook, iPad e Windows",
    ],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    inStock: true,
    rating: 4.6,
    reviewCount: 312,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Bruno K.", rating: 5, comment: "Imprescindível para o MacBook. HDMI 4K funciona perfeito.", date: "11/05/2026" },
      { author: "Priscila M.", rating: 4, comment: "Muito prático. USB-C e HDMI ao mesmo tempo sem perda de qualidade.", date: "03/05/2026" },
      { author: "Diego N.", rating: 5, comment: "Ethernet Gigabit fez muita diferença no home office.", date: "19/04/2026" },
    ],
  },
  {
    id: "14",
    slug: "teclado-mecanico-gamer",
    name: "Teclado Mecânico Gamer TKL RGB",
    shortName: "Teclado Mecânico TKL",
    category: "Gadgets & Eletrônicos",
    price: 199,
    originalPrice: 299,
    description: "Teclado mecânico TKL (87 teclas) com switches blue, iluminação RGB por tecla, anti-ghosting 100% e cabo USB trançado removível.",
    features: [
      "Layout TKL 87 teclas compacto",
      "Switches mecânicos blue (clicky)",
      "RGB individual por tecla",
      "Anti-ghosting 100% NKRO",
      "Cabo USB trançado removível",
      "Construção em alumínio",
    ],
    imageUrl: "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=600&q=80",
    badge: "Gamer",
    inStock: true,
    rating: 4.8,
    reviewCount: 428,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Gabriel S.", rating: 5, comment: "Som dos switches é incrível. RGB muito bem calibrado.", date: "13/05/2026" },
      { author: "Vinícius A.", rating: 5, comment: "Melhor teclado que já usei. Anti-ghosting perfeito.", date: "05/05/2026" },
      { author: "Renan O.", rating: 4, comment: "Ótimo custo-benefício. Alumínio dá sensação premium.", date: "21/04/2026" },
    ],
  },
  {
    id: "15",
    slug: "mouse-gamer-rgb",
    name: "Mouse Gamer RGB 12400 DPI",
    shortName: "Mouse Gamer 12400 DPI",
    category: "Gadgets & Eletrônicos",
    price: 89,
    originalPrice: 140,
    description: "Mouse gamer com sensor óptico de 12400 DPI, 7 botões programáveis, iluminação RGB e cabo trançado de 1,8m. Design ergonômico para longas sessões.",
    features: [
      "Sensor óptico 12400 DPI ajustável",
      "7 botões programáveis",
      "Iluminação RGB 16 milhões de cores",
      "Polling rate 1000Hz",
      "Cabo trançado 1,8m",
      "Design ergonômico destro",
    ],
    imageUrl: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&q=80",
    badge: "Gamer",
    inStock: true,
    rating: 4.7,
    reviewCount: 356,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Fábio R.", rating: 5, comment: "Precisão excelente. DPI variável faz muita diferença nos jogos.", date: "12/05/2026" },
      { author: "Igor S.", rating: 4, comment: "Muito confortável para longas sessões. RGB bonito.", date: "04/05/2026" },
      { author: "Marcelo T.", rating: 5, comment: "Melhor mouse gamer de entrada que já tive.", date: "20/04/2026" },
    ],
  },
  {
    id: "16",
    slug: "relogio-solar-militar",
    name: "Relógio Solar Militar com GPS e Bússola",
    shortName: "Relógio Solar Militar",
    category: "Camping & Aventura",
    price: 249,
    originalPrice: 380,
    description: "Relógio outdoor militar com carregamento solar, GPS, altímetro, barômetro, bússola digital e resistência militar MIL-STD-810G.",
    features: [
      "Carregamento solar + bateria 30 dias",
      "GPS, GLONASS e BeiDou",
      "Altímetro e barômetro",
      "Bússola digital",
      "Resistência militar MIL-STD-810G",
      "Resistente à água 10ATM",
    ],
    imageUrl: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&q=80",
    badge: "Aventura",
    inStock: true,
    rating: 4.8,
    reviewCount: 203,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Sérgio M.", rating: 5, comment: "Preciso nas trilhas. Barômetro avisa mudança de clima com antecedência.", date: "11/05/2026" },
      { author: "Wellington P.", rating: 5, comment: "Resistente mesmo! Levei para mergulho e continuou funcionando.", date: "03/05/2026" },
      { author: "Claudia R.", rating: 4, comment: "GPS preciso e bateria solar excelente para expedições longas.", date: "19/04/2026" },
    ],
  },
  {
    id: "17",
    slug: "camera-acao-4k",
    name: "Câmera de Ação 4K 60fps à Prova d'Água",
    shortName: "Câmera de Ação 4K",
    category: "Camping & Aventura",
    price: 279,
    originalPrice: 420,
    description: "Câmera de ação 4K 60fps com estabilização EIS, resistente à água até 30m, tela touchscreen 2' e acessórios de fixação inclusos.",
    features: [
      "Vídeo 4K@60fps e fotos 20MP",
      "Estabilização EIS 6 eixos",
      "Resistente à água até 30m",
      "Tela touchscreen 2 polegadas",
      "Wi-Fi e Bluetooth integrados",
      "Kit completo de acessórios",
    ],
    imageUrl: "https://images.unsplash.com/photo-1502920514313-52581002a659?w=600&q=80",
    badge: "Aventura",
    inStock: true,
    rating: 4.7,
    reviewCount: 178,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Tiago B.", rating: 5, comment: "Imagem perfeita no surf. Estabilização impressiona.", date: "10/05/2026" },
      { author: "Vanessa C.", rating: 4, comment: "Ótima para trilhas e bikes. Imagem 4K muito nítida.", date: "02/05/2026" },
      { author: "Alex F.", rating: 5, comment: "Melhor câmera de ação custo-benefício do mercado.", date: "18/04/2026" },
    ],
  },
  {
    id: "18",
    slug: "caixa-som-bluetooth-ipx7",
    name: "Caixa de Som Bluetooth IPX7 à Prova d'Água",
    shortName: "Caixa Bluetooth IPX7",
    category: "Gadgets & Eletrônicos",
    price: 149,
    originalPrice: 220,
    description: "Caixa de som portátil com 30W RMS, Bluetooth 5.3, resistência IPX7, bateria de 24h, TWS para pareamento duplo e graves potentes.",
    features: [
      "30W RMS com graves reforçados",
      "Bluetooth 5.3 — alcance 15m",
      "Resistência IPX7 submersível",
      "Bateria 24h de reprodução",
      "TWS — duplo pareamento",
      "Entrada auxiliar P2 e USB",
    ],
    imageUrl: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80",
    badge: "Mais Vendido",
    inStock: true,
    rating: 4.8,
    reviewCount: 389,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Marcos A.", rating: 5, comment: "Som potente e graves incríveis. Usou no camping de 3 dias sem carregar.", date: "12/05/2026" },
      { author: "Letícia R.", rating: 5, comment: "Resistência à água impressiona. Jogou na piscina e continuou tocando.", date: "04/05/2026" },
      { author: "Murilo S.", rating: 4, comment: "Ótima caixa. TWS com outra igual ficou ainda mais potente.", date: "20/04/2026" },
    ],
  },
  {
    id: "19",
    slug: "lampada-inteligente-rgb",
    name: "Lâmpada Inteligente RGB Wi-Fi",
    shortName: "Lâmpada RGB Wi-Fi",
    category: "Automação Residencial",
    price: 59,
    originalPrice: 90,
    description: "Lâmpada LED inteligente 16 milhões de cores RGB, controle por app, compatível com Alexa e Google Home. Sem hub necessário.",
    features: [
      "16 milhões de cores RGB + branco quente/frio",
      "Controle por app ou voz",
      "Compatível com Alexa e Google Home",
      "Potência 9W equivale a 60W",
      "Vida útil de 25.000 horas",
      "Cenas e horários programáveis",
    ],
    imageUrl: "https://images.unsplash.com/photo-1565814636199-ae8133055c1c?w=600&q=80",
    badge: "Smart Home",
    inStock: true,
    rating: 4.5,
    reviewCount: 178,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Davi L.", rating: 5, comment: "Configurou em 2 minutos com a Alexa. Cores incríveis.", date: "14/05/2026" },
      { author: "Natan S.", rating: 4, comment: "App funciona bem. Cenas de cinema e festa são demais.", date: "28/04/2026" },
      { author: "Kevin O.", rating: 5, comment: "Transformou o quarto. Preço ótimo para essa qualidade.", date: "10/04/2026" },
    ],
  },
  {
    id: "20",
    slug: "tomada-inteligente-wifi",
    name: "Tomada Inteligente Wi-Fi 16A",
    shortName: "Tomada Inteligente Wi-Fi",
    category: "Automação Residencial",
    price: 69,
    originalPrice: 100,
    description: "Tomada smart Wi-Fi 16A com monitoramento de consumo de energia, timer programável, controle por voz e proteção contra sobrecarga.",
    features: [
      "Controle remoto por app",
      "Monitoramento de consumo em tempo real",
      "Compatível com Alexa e Google Home",
      "Timer e agendamentos programáveis",
      "Proteção contra sobrecarga e surtos",
      "Instalação plug & play",
    ],
    imageUrl: "https://images.unsplash.com/photo-1586473219010-2ffc57b0d282?w=600&q=80",
    inStock: true,
    rating: 4.6,
    reviewCount: 93,
    deliveryDays: "4–7 dias úteis",
    reviews: [
      { author: "Luan C.", rating: 5, comment: "Monitoramento de consumo é muito útil. Descobri que meu ar-condicionado gasta muito.", date: "11/05/2026" },
      { author: "Yuri M.", rating: 4, comment: "Fácil de instalar e configurar. App é intuitivo.", date: "25/04/2026" },
      { author: "Enzo F.", rating: 5, comment: "Comprei 4 unidades. Funcionam perfeitamente com a Alexa.", date: "08/04/2026" },
    ],
  },
  {
    id: "21",
    slug: "power-bank-50000mah-liggi",
    name: "Power Bank 50.000mAh Liggi com Cabo Carregador",
    shortName: "Power Bank Liggi 50000mAh",
    category: "Gadgets & Eletrônicos",
    price: 219,
    originalPrice: 299,
    description: "Carregador portátil de alta capacidade 50.000mAh da Liggi com cabo carregador incluso, 2 saídas USB-A, entrada Micro-USB e indicador de carga LED. Ideal para viagens longas e camping.",
    features: [
      "Capacidade de 50.000mAh",
      "2 saídas USB-A simultâneas",
      "Cabo carregador incluso",
      "Indicador de carga LED",
      "Entrada Micro-USB",
      "Proteção contra sobrecarga e curto-circuito",
    ],
    imageUrl: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80",
    badge: "Viagem",
    inStock: true,
    rating: 4.8,
    reviewCount: 1043,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Lucas M.", rating: 5, comment: "Carregou meu celular mais de 10 vezes numa viagem de 5 dias. Incrível!", date: "15/05/2026" },
      { author: "Patrícia S.", rating: 4, comment: "Ótima capacidade, cabo incluso é muito prático.", date: "02/05/2026" },
      { author: "Gabriel R.", rating: 5, comment: "Melhor power bank que já tive. Vale cada centavo.", date: "19/04/2026" },
    ],
  },
  {
    id: "22",
    slug: "roteador-mesh-deco-m4",
    name: "Roteador Mesh Wi-Fi TP-Link Deco M4 AC1200 Kit 2 unidades",
    shortName: "TP-Link Deco M4 Mesh",
    category: "Automação Residencial",
    price: 449,
    originalPrice: 649,
    description: "Sistema Wi-Fi Mesh TP-Link Deco M4 com 2 unidades, cobertura de até 350m², dual band AC1200 e suporte a até 100 dispositivos. Elimina zonas mortas de Wi-Fi e garante sinal forte em todos os cômodos da casa. Gerenciamento simples pelo app Deco.",
    features: [
      "Cobertura de até 350m² com 2 unidades",
      "Dual Band AC1200: 867Mbps (5GHz) + 300Mbps (2.4GHz)",
      "Suporte a até 100 dispositivos simultâneos",
      "2 portas Gigabit LAN/WAN por unidade",
      "Controle parental com bloqueio por perfil",
      "Roaming inteligente — troca automática entre unidades",
      "Gerenciamento pelo app Deco (iOS e Android)",
      "Garantia TP-Link de 5 anos",
    ],
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    badge: "Smart Home",
    inStock: true,
    rating: 4.8,
    reviewCount: 342,
    deliveryDays: "5–8 dias úteis",
    reviews: [
      { author: "Rodrigo F.", rating: 5, comment: "Acabou com o Wi-Fi fraco no quarto. Sinal perfeito em toda a casa agora.", date: "18/05/2026" },
      { author: "Patricia M.", rating: 5, comment: "Instalação muito fácil pelo app. Recomendo para casas grandes.", date: "05/05/2026" },
      { author: "Anderson L.", rating: 4, comment: "Ótimo produto, só precisei reiniciar uma vez. Cobertura excelente.", date: "22/04/2026" },
    ],
  },
  {
    id: "23",
    slug: "gimbal-estabilizador-celular-3-eixos-ia",
    name: "Gimbal Estabilizador de Celular 3 Eixos com IA e Tripé Dobrável",
    shortName: "Gimbal 3 Eixos com IA",
    category: "Gadgets & Eletrônicos",
    price: 129,
    originalPrice: 199,
    description: "Estabilizador gimbal profissional de 3 eixos com rastreamento facial por IA, tripé dobrável integrado e controle por gestos. Compatível com iPhone e Android. Ideal para criadores de conteúdo, lives e vlogs.",
    features: [
      "Estabilização em 3 eixos para vídeos suaves",
      "Rastreamento facial e corporal por IA automático",
      "Tripé dobrável integrado — sem acessórios extras",
      "Controle por gestos para fotos e vídeos sem toque",
      "Rotação 360° e modos panorâmico e time-lapse",
      "Compatível com iPhone e Android (até 280g)",
      "Bateria embutida com até 8h de uso",
      "Conexão Bluetooth estável",
    ],
    imageUrl: "https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=600&q=80",
    badge: "Criadores",
    inStock: true,
    rating: 4.7,
    reviewCount: 2341,
    deliveryDays: "5–10 dias úteis",
    reviews: [
      { author: "Thiago R.", rating: 5, comment: "O rastreamento facial é incrível, segue perfeitamente sem travar. Vale cada centavo.", date: "20/05/2026" },
      { author: "Camila F.", rating: 5, comment: "Melhorou muito meus vídeos. O tripé integrado é muito prático para gravar sozinha.", date: "03/05/2026" },
      { author: "Bruno S.", rating: 4, comment: "Funciona muito bem. App conecta fácil e os modos automáticos impressionam.", date: "15/04/2026" },
    ],
  },
];
